const Questions = [
  {
    botId: 0,
    questions: [
      "Do you believe in aliens?",
      "How many times have you been to Disney?",
      "Sure you saw my movie, right?",
      "What year did Disneyland open?",
      "Who trained Hercules to be a hero?",
      "What is the name of Andy’s neighbor in Toy Story?",
      "What does Hakuna Matata mean?",
      "How many fingers does Mickey Mouse have?",
      "Genie was stuck in the lamp for how many years before Aladdin found him?",
      "Which Disney Princess did Lily James portray in a 2015 live action-remake?",
      "What was the first Pixar movie?",
      "What are the three mountains in Magic Kingdom?",
    ],
  },
  {
    botId: 1,
    questions: [
      "What was Freddie Mercury‘s real name?",
      "Who was the very first American Idol winner?",
      "Which member of the Avengers had a brief stint as a pop star?",
      "What was Madonna‘s first top 10 hit",
      "Which classical composer was deaf?",
      "What video beat “Thriller” for Video of the Year at the first-ever MTV Video Music Awards?",
      "Who was the first woman to have four country albums reach No. 1 on the Billboard 200?",
      "Which astronomer is namedropped in “Bohemian Rhapsody?”",
      "Who was the first lead guitarist of Metallica?",
    ],
  },
  {
    botId: 2,
    questions: [
      "What sport is best known as the ‘king of sports’?",
      "What’s the national sport of Canada?",
      "The classic 1980 movie called Raging Bull is about which real-life boxer?",
      "Who has won more tennis grand slam titles, Venus Williams or Serena Williams?",
      "Which boxer fought against Muhammad Ali and won?",
      "What does NBA stand for?",
      "How long is a marathon?",
      "How many players are on a baseball team?",
      "Best soccer player in the world?",
      "In soccer, what body part can’t touch the ball?",
      "In what year were women allowed to compete in the modern Olympic games and in what sport?",
      "What is the only sport to be played on the moon?",
      "How many minutes was the longest recorded point in the history of tennis?",
    ],
  },
  {
    botId: 3,
    questions: [
      "What's the scariest dream you've ever had?",
      "What animal would you want to be reincarnated as?",
      "If you could visit one planet, which would it be?",
      "What super power do you wish you had?",
      "What’s your very first memory?",
      "What makes you happiest?",
      "What country do you most want to travel to?",
      "Which foreign language would you like to learn?",
      "What’s your favorite color?",
      "Do you believe in aliens?",
      "How would you spend 100 million dollars?",
      "What’s your favorite line from a movie or book?",
      "What’s your all-time favorite quotes?",
      "What skill do you wish you had?",
      "What is your nickname?",
      "What would your dream house look like?",
      "What is one goal you have for the near future?",
      "Do you think you could live in outer space for a year?",
      "What item do you collect?",
    ],
  },
];

export { Questions };
